CREATE TABLE profile (
                       id                 BIGINT       PRIMARY KEY DEFAULT 1,
                       display_name       VARCHAR(120) NOT NULL,
                       professional_title VARCHAR(160) NOT NULL,
                       short_bio          VARCHAR(500) NOT NULL,
                       about_markdown     TEXT,
                       public_location    VARCHAR(120),
                       public_email       VARCHAR(255)

                        CONSTRAINT profile_single_row CHECK (id = 1)
);

CREATE TABLE professional_link (
                                 id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 profile_id    BIGINT        NOT NULL,
                                 label         VARCHAR(80)   NOT NULL,
                                 url           VARCHAR(2048) NOT NULL,
                                 display_order INTEGER       NOT NULL DEFAULT 0,

                                 CONSTRAINT professional_link_profile_fk
                                   FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE
);

CREATE INDEX professional_link_profile_order_idx
  ON professional_link (profile_id, display_order);
