CREATE TABLE skill (
                     id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     profile_id    BIGINT      NOT NULL,
                     name          VARCHAR(80) NOT NULL,
                     category      VARCHAR(60) NOT NULL,
                     display_order INTEGER     NOT NULL DEFAULT 0,

                     CONSTRAINT skill_profile_fk
                       FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE,

                     CONSTRAINT skill_unique_name
                       UNIQUE (profile_id, name)
);
