CREATE TABLE experience (
                          id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          profile_id    BIGINT       NOT NULL,
                          organization  VARCHAR(120) NOT NULL,
                          title         VARCHAR(120) NOT NULL,
                          location      VARCHAR(120) NOT NULL,
                          start_date    DATE         NOT NULL,
                          end_date      DATE,
                          description   TEXT         NOT NULL,
                          display_order INTEGER      NOT NULL DEFAULT 0,

                          CONSTRAINT experience_profile_fk
                            FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE,

                          CONSTRAINT experience_dates_check
                            CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE education (
                         id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         profile_id    BIGINT       NOT NULL,
                         institution   VARCHAR(160) NOT NULL,
                         degree        VARCHAR(160) NOT NULL,
                         field         VARCHAR(160) NOT NULL,
                         location      VARCHAR(120) NOT NULL,
                         start_date    DATE         NOT NULL,
                         end_date      DATE,
                         description   TEXT         NOT NULL,
                         display_order INTEGER      NOT NULL DEFAULT 0,

                         CONSTRAINT education_profile_fk
                           FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE,

                         CONSTRAINT education_dates_check
                           CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE certification (
                             id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             profile_id     BIGINT        NOT NULL,
                             name           VARCHAR(160)  NOT NULL,
                             issuer         VARCHAR(120)  NOT NULL,
                             issued_at      DATE          NOT NULL,
                             expires_at     DATE,
                             credential_url VARCHAR(2048),
                             display_order  INTEGER       NOT NULL DEFAULT 0,

                             CONSTRAINT certification_profile_fk
                               FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE,

                             CONSTRAINT certification_dates_check
                               CHECK (expires_at IS NULL OR expires_at >= issued_at)
);
