-- Projet (étape 17). Ni média ni technologie avant les étapes 18 et 27 (D-Y).

CREATE TABLE project (
                       id                   BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title                VARCHAR(160)  NOT NULL,
                       slug                 VARCHAR(160)  NOT NULL,
                       short_description    VARCHAR(500)  NOT NULL,
                       description_markdown TEXT          NOT NULL,
                       stage                VARCHAR(20)   NOT NULL,
                       visibility           VARCHAR(20)   NOT NULL,
                       start_date           DATE          NOT NULL,
                       end_date             DATE,
                       repository_url       VARCHAR(2048),
                       demo_url             VARCHAR(2048),
                       featured             BOOLEAN       NOT NULL DEFAULT FALSE,
                       display_order        INTEGER       NOT NULL DEFAULT 0,

                       -- Slug public : unique et compatible URL (D-X). Génération et collisions : étape 22.
                       CONSTRAINT project_slug_unique
                         UNIQUE (slug),

                       CONSTRAINT project_slug_format_check
                         CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),

                       CONSTRAINT project_stage_check
                         CHECK (stage IN ('IN_PROGRESS', 'COMPLETED')),

                       CONSTRAINT project_visibility_check
                         CHECK (visibility IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),

                       -- Invariant 17 (période), comme experience et education.
                       CONSTRAINT project_dates_check
                         CHECK (end_date IS NULL OR end_date >= start_date),

                       -- Invariant 21 (D-T) : un projet est en cours si et seulement s'il n'a pas de date de fin.
                       CONSTRAINT project_stage_matches_dates_check
                         CHECK ((stage = 'IN_PROGRESS') = (end_date IS NULL))
);
