-- Vocabulaire des technologies et association aux projets (étape 18).
-- Distinct des tags éditoriaux (D21). Couverture et captures des projets : étape 27 (D-AD).

CREATE TABLE technology (
                          id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name          VARCHAR(80) NOT NULL,
                          slug          VARCHAR(80) NOT NULL,
                          display_order INTEGER     NOT NULL DEFAULT 0,

                          CONSTRAINT technology_slug_unique
                            UNIQUE (slug),

                          CONSTRAINT technology_slug_format_check
                            CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

-- Invariant 22 : « Java » et « java » désignent la même technologie (D-AA).
CREATE UNIQUE INDEX technology_name_unique_idx
  ON technology (lower(name));

CREATE TABLE project_technology (
                                  project_id    BIGINT NOT NULL,
                                  technology_id BIGINT NOT NULL,

                                  -- Invariant 23 : une technologie au plus une fois par projet.
                                  CONSTRAINT project_technology_pk
                                    PRIMARY KEY (project_id, technology_id),

                                  CONSTRAINT project_technology_project_fk
                                    FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE,

                                  -- Invariant 22 : une technologie utilisée par un projet ne peut pas être supprimée.
                                  CONSTRAINT project_technology_technology_fk
                                    FOREIGN KEY (technology_id) REFERENCES technology (id) ON DELETE RESTRICT
);
