-- Publication, modèle commun à ARTICLE et NEWS (étape 19).
-- Catégorie et tags : étape 20 ; transitions de statut : étape 21 ; couverture : étape 27 (D-AF).

CREATE TABLE publication (
                           id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           type             VARCHAR(20)   NOT NULL,
                           title            VARCHAR(160)  NOT NULL,
                           slug             VARCHAR(160)  NOT NULL,
                           summary          VARCHAR(500)  NOT NULL,
                           content_markdown TEXT          NOT NULL,
                           status           VARCHAR(20)   NOT NULL,
                           published_at     TIMESTAMPTZ,
                           featured         BOOLEAN       NOT NULL DEFAULT FALSE,
                           seo_title        VARCHAR(120),
                           seo_description  VARCHAR(300),
                           created_at       TIMESTAMPTZ   NOT NULL,
                           updated_at       TIMESTAMPTZ   NOT NULL,

                           -- Un seul espace de slugs pour ARTICLE et NEWS : /publications/{slug} (D-AL).
                           CONSTRAINT publication_slug_unique
                             UNIQUE (slug),

                           CONSTRAINT publication_slug_format_check
                             CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),

                           CONSTRAINT publication_type_check
                             CHECK (type IN ('ARTICLE', 'NEWS')),

                           CONSTRAINT publication_status_check
                             CHECK (status IN ('DRAFT', 'IN_REVIEW', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED')),

                           -- Invariant 24 (D-AI) : une publication planifiée ou publiée a toujours une date de publication.
                           CONSTRAINT publication_published_at_check
                             CHECK (status NOT IN ('SCHEDULED', 'PUBLISHED') OR published_at IS NOT NULL)
);
