-- Taxonomie éditoriale (étape 20) : catégories et tags, distincts des technologies des projets (D21).

CREATE TABLE category (
                        id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name        VARCHAR(80)  NOT NULL,
                        slug        VARCHAR(80)  NOT NULL,
                        description VARCHAR(500),

                        CONSTRAINT category_slug_unique
                          UNIQUE (slug),

                        CONSTRAINT category_slug_format_check
                          CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

-- Invariant 25 : unicité du nom sans tenir compte de la casse (D-AO).
CREATE UNIQUE INDEX category_name_unique_idx
  ON category (lower(name));

CREATE TABLE tag (
                   id   BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                   name VARCHAR(60) NOT NULL,
                   slug VARCHAR(60) NOT NULL,

                   CONSTRAINT tag_slug_unique
                     UNIQUE (slug),

                   CONSTRAINT tag_slug_format_check
                     CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

CREATE UNIQUE INDEX tag_name_unique_idx
  ON tag (lower(name));
