-- Séries d'articles (étape 23, D-BE, D-BF). Aucune colonne de statut : une série n'a pas de workflow
-- éditorial propre (01 §8) ; elle est publique dès qu'un de ses articles l'est (D-BG). Couverture : étape 27.

CREATE TABLE series (
                      id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title                VARCHAR(160) NOT NULL,
                      slug                 VARCHAR(160) NOT NULL,
                      description_markdown TEXT         NOT NULL,

                      CONSTRAINT series_slug_unique
                        UNIQUE (slug),

                      CONSTRAINT series_slug_format_check
                        CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
);

-- Cible de la clé étrangère composite de series_item : seule la base peut empêcher qu'un article déjà
-- dans une série devienne une NEWS, puisque le module publication ignore les séries (04 §5, D-BF).
ALTER TABLE publication
  ADD CONSTRAINT publication_id_type_unique
    UNIQUE (id, type);

CREATE TABLE series_item (
                           series_id        BIGINT      NOT NULL,
                           publication_id   BIGINT      NOT NULL,
                           -- Jamais écrite par l'application : sert uniquement à la clé étrangère composite.
                           publication_type VARCHAR(20) NOT NULL DEFAULT 'ARTICLE',
                           position         INTEGER     NOT NULL,

                           -- Invariant 3 : une position n'existe qu'une fois dans une même série.
                           CONSTRAINT series_item_pk
                             PRIMARY KEY (series_id, position),

                           -- Invariant 2 (D05) : un article appartient au maximum à une série.
                           CONSTRAINT series_item_publication_unique
                             UNIQUE (publication_id),

                           CONSTRAINT series_item_position_check
                             CHECK (position > 0),

                           -- Invariant 1 (D05) : une NEWS n'appartient jamais à une série.
                           CONSTRAINT series_item_article_only_check
                             CHECK (publication_type = 'ARTICLE'),

                           CONSTRAINT series_item_series_fk
                             FOREIGN KEY (series_id) REFERENCES series (id) ON DELETE CASCADE,

                           -- Supprimer un article le retire de sa série ; changer son type est refusé.
                           CONSTRAINT series_item_publication_fk
                             FOREIGN KEY (publication_id, publication_type) REFERENCES publication (id, type)
                               ON DELETE CASCADE
);
