-- Catalogue des médias (étape 27.1, D-BU) : métadonnées des fichiers stockés par MediaStorage.
-- Le type MIME n'est pas stocké : il se déduit de l'extension de la clé (D-BP). Les rattachements aux
-- contenus (couvertures, captures, avatar, CV) arrivent avec les étapes 27.2 à 27.4.

CREATE TABLE media (
                     id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     storage_key   VARCHAR(40)  NOT NULL,
                     original_name VARCHAR(255) NOT NULL,
                     size_bytes    BIGINT       NOT NULL,
                     width         INTEGER,
                     height        INTEGER,
                     alt_text      VARCHAR(300),
                     created_at    TIMESTAMPTZ  NOT NULL,

                     CONSTRAINT media_storage_key_unique
                       UNIQUE (storage_key),

                     -- Clé opaque : UUID hexadécimal et extension d'un format accepté (D08, D-BP).
                     CONSTRAINT media_storage_key_format_check
                       CHECK (storage_key ~ '^[0-9a-f]{32}\.(png|jpg|webp|pdf)$'),

                     CONSTRAINT media_original_name_check
                       CHECK (btrim(original_name) <> ''),

                     -- 01 §12 : 5 Mio pour une image, 10 Mio pour un PDF (D-BR).
                     CONSTRAINT media_size_check
                       CHECK (size_bytes > 0
                         AND size_bytes <= CASE WHEN storage_key LIKE '%.pdf' THEN 10485760 ELSE 5242880 END),

                     -- Une image a toujours ses dimensions, un PDF jamais (D-BU).
                     CONSTRAINT media_dimensions_check
                       CHECK (CASE WHEN storage_key LIKE '%.pdf'
                                THEN width IS NULL AND height IS NULL
                                ELSE width IS NOT NULL AND height IS NOT NULL AND width > 0 AND height > 0 END)
);
