-- Messages du formulaire de contact (étape 30, D-CG, D-CH). Aucune adresse IP n'est stockée (02 §23) :
-- la limitation de débit est une affaire de la requête HTTP (étape 48), pas du message.

CREATE TABLE contact_message (
                               id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name       VARCHAR(100)  NOT NULL,
                               email      VARCHAR(254)  NOT NULL,
                               subject    VARCHAR(200)  NOT NULL,
                               message    VARCHAR(5000) NOT NULL,
                               status     VARCHAR(20)   NOT NULL,
                               created_at TIMESTAMPTZ   NOT NULL,
                               updated_at TIMESTAMPTZ   NOT NULL,

                               -- Mêmes règles que ContactMessage (doublées ici, principe D-N) : au moins un caractère qui n'est pas un espace.
                               CONSTRAINT contact_message_name_check
                                 CHECK (name ~ '[^[:space:]]'),

                               CONSTRAINT contact_message_email_check
                                 CHECK (email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),

                               CONSTRAINT contact_message_subject_check
                                 CHECK (subject ~ '[^[:space:]]'),

                               CONSTRAINT contact_message_message_check
                                 CHECK (message ~ '[^[:space:]]'),

                               CONSTRAINT contact_message_status_check
                                 CHECK (status IN ('NEW', 'READ', 'PROCESSED', 'ARCHIVED')),

                               CONSTRAINT contact_message_dates_check
                                 CHECK (updated_at >= created_at)
);
