package com.scalke.portfolio.backend.shared.error;

public enum ErrorCode {

    // génériques
    RESOURCE_NOT_FOUND,
    AUTHENTICATION_REQUIRED,
    INVALID_CREDENTIALS,
    TOO_MANY_LOGIN_ATTEMPTS,
    ACCESS_DENIED,
    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    INTERNAL_ERROR,

    // vocabulaires (taxonomie, technologies)
    NAME_ALREADY_USED,
    TERM_STILL_USED,

    // publication
    SLUG_ALREADY_USED,
    INVALID_PUBLICATION_TRANSITION,
    SLUG_LOCKED,

    // series
    NEWS_CANNOT_JOIN_SERIES,
    ARTICLE_ALREADY_IN_SERIES,

    // media
    MEDIA_STILL_REFERENCED,
    UNSUPPORTED_MEDIA_FORMAT,
    MEDIA_TOO_LARGE,

    // contact
    INVALID_CONTACT_MESSAGE_TRANSITION,
    TOO_MANY_CONTACT_MESSAGES
}
