/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_6"];
        put?: never;
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_6"];
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contact-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_7"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contact-messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/contact-messages/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changeStatus_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_4"];
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch: operations["update_7"];
        trace?: never;
    };
    "/admin/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put: operations["update_5"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put: operations["update_4"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/publications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put: operations["update_3"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/publications/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changeStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/series/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update_2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/series/{id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changeChapters"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["current"];
        put?: never;
        post: operations["open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_1"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/technologies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/technologies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/media/{storageKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPublications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/publications/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/publications/{slug}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSeriesNavigation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/series/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminCategoryResponse: {
            description: string | null;
            /** Format: int64 */
            id: number;
            name: string;
            slug: string;
        };
        AdminContactMessageResponse: {
            /** Format: date-time */
            createdAt: string;
            email: string;
            /** Format: int64 */
            id: number;
            message: string;
            name: string;
            /** @enum {string} */
            status: "NEW" | "READ" | "PROCESSED" | "ARCHIVED";
            subject: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AdminContactMessageSummaryResponse: {
            /** Format: date-time */
            createdAt: string;
            email: string;
            /** Format: int64 */
            id: number;
            name: string;
            /** @enum {string} */
            status: "NEW" | "READ" | "PROCESSED" | "ARCHIVED";
            subject: string;
        };
        AdminMediaResponse: {
            altText: string | null;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            format: "PNG" | "JPEG" | "WEBP" | "PDF";
            /** Format: int32 */
            height: number | null;
            /** Format: int64 */
            id: number;
            mimeType: string;
            originalName: string;
            /** Format: int64 */
            sizeBytes: number;
            url: string;
            /** Format: int32 */
            width: number | null;
        };
        AdminProfileResponse: {
            aboutMarkdown: string | null;
            /** Format: int64 */
            avatarMediaId: number | null;
            certifications: components["schemas"]["Certification"][];
            /** Format: int64 */
            cvMediaId: number | null;
            displayName: string;
            educations: components["schemas"]["Education"][];
            experiences: components["schemas"]["Experience"][];
            links: components["schemas"]["Link"][];
            professionalTitle: string;
            publicEmail: string | null;
            publicLocation: string | null;
            shortBio: string;
            skills: components["schemas"]["Skill"][];
        };
        AdminProjectResponse: {
            /** Format: int64 */
            coverMediaId: number | null;
            demoUrl: string | null;
            descriptionMarkdown: string;
            /** Format: int32 */
            displayOrder: number;
            /** Format: date */
            endDate: string | null;
            featured: boolean;
            /** Format: int64 */
            id: number;
            repositoryUrl: string | null;
            screenshots: components["schemas"]["Screenshot"][];
            shortDescription: string;
            slug: string;
            slugLocked: boolean;
            /** @enum {string} */
            stage: "IN_PROGRESS" | "COMPLETED";
            /** Format: date */
            startDate: string;
            technologyIds: number[];
            title: string;
            /** @enum {string} */
            visibility: "DRAFT" | "PUBLISHED" | "ARCHIVED";
        };
        AdminProjectSummaryResponse: {
            /** Format: int32 */
            displayOrder: number;
            featured: boolean;
            /** Format: int64 */
            id: number;
            slug: string;
            /** @enum {string} */
            stage: "IN_PROGRESS" | "COMPLETED";
            title: string;
            /** @enum {string} */
            visibility: "DRAFT" | "PUBLISHED" | "ARCHIVED";
        };
        AdminPublicationResponse: {
            /** Format: int64 */
            categoryId: number | null;
            contentMarkdown: string;
            /** Format: int64 */
            coverMediaId: number | null;
            /** Format: date-time */
            createdAt: string;
            featured: boolean;
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            publishedAt: string | null;
            seoDescription: string | null;
            seoTitle: string | null;
            slug: string;
            slugLocked: boolean;
            /** @enum {string} */
            status: "DRAFT" | "IN_REVIEW" | "SCHEDULED" | "PUBLISHED" | "ARCHIVED";
            summary: string;
            tagIds: number[];
            title: string;
            /** @enum {string} */
            type: "ARTICLE" | "NEWS";
            /** Format: date-time */
            updatedAt: string;
        };
        AdminPublicationSummaryResponse: {
            featured: boolean;
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            publishedAt: string | null;
            slug: string;
            /** @enum {string} */
            status: "DRAFT" | "IN_REVIEW" | "SCHEDULED" | "PUBLISHED" | "ARCHIVED";
            title: string;
            /** @enum {string} */
            type: "ARTICLE" | "NEWS";
            /** Format: date-time */
            updatedAt: string;
        };
        AdminSeriesResponse: {
            chapters: components["schemas"]["Chapter"][];
            /** Format: int64 */
            coverMediaId: number | null;
            descriptionMarkdown: string;
            /** Format: int64 */
            id: number;
            slug: string;
            slugLocked: boolean;
            title: string;
        };
        AdminSeriesSummaryResponse: {
            /** Format: int32 */
            chapterCount: number;
            /** Format: int64 */
            id: number;
            slug: string;
            title: string;
        };
        AdminSessionResponse: {
            /** Format: date-time */
            lastLoginAt: string;
            login: string;
        };
        AdminTagResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            slug: string;
        };
        AdminTechnologyResponse: {
            /** Format: int32 */
            displayOrder: number;
            /** Format: int64 */
            id: number;
            name: string;
            slug: string;
        };
        Certification: {
            credentialUrl?: string;
            /** Format: date */
            expiresAt?: string;
            /** Format: date */
            issuedAt: string;
            issuer: string;
            name: string;
        };
        CertificationResponse: {
            credentialUrl: string | null;
            /** Format: date */
            expiresAt: string | null;
            /** Format: date */
            issuedAt: string;
            issuer: string;
            name: string;
        };
        ChangeContactMessageStatusRequest: {
            /** @enum {string} */
            status: "NEW" | "READ" | "PROCESSED" | "ARCHIVED";
        };
        ChangePublicationStatusRequest: {
            /** Format: date-time */
            publishedAt?: string;
            /** @enum {string} */
            status: "DRAFT" | "IN_REVIEW" | "SCHEDULED" | "PUBLISHED" | "ARCHIVED";
        };
        ChangeSeriesChaptersRequest: {
            publicationIds: number[];
        };
        Chapter: {
            /** Format: int32 */
            position: number;
            /** Format: int64 */
            publicationId: number;
            slug: string;
            /** @enum {string} */
            status: "DRAFT" | "IN_REVIEW" | "SCHEDULED" | "PUBLISHED" | "ARCHIVED";
            title: string;
        };
        ChapterLinkResponse: {
            /** Format: int32 */
            position: number;
            slug: string;
            title: string;
        };
        CreatePublicationRequest: {
            /** Format: int64 */
            categoryId?: number;
            contentMarkdown: string;
            /** Format: int64 */
            coverMediaId?: number;
            featured?: boolean;
            seoDescription?: string;
            seoTitle?: string;
            slug?: string;
            summary: string;
            tagIds?: number[];
            title: string;
            /** @enum {string} */
            type: "ARTICLE" | "NEWS";
        };
        Education: {
            degree: string;
            description: string;
            /** Format: date */
            endDate?: string;
            field: string;
            institution: string;
            location: string;
            /** Format: date */
            startDate: string;
        };
        EducationResponse: {
            degree: string;
            description: string;
            /** Format: date */
            endDate: string | null;
            field: string;
            institution: string;
            location: string;
            /** Format: date */
            startDate: string;
        };
        Experience: {
            description: string;
            /** Format: date */
            endDate?: string;
            location: string;
            organization: string;
            /** Format: date */
            startDate: string;
            title: string;
        };
        ExperienceResponse: {
            description: string;
            /** Format: date */
            endDate: string | null;
            location: string;
            organization: string;
            /** Format: date */
            startDate: string;
            title: string;
        };
        Link: {
            label: string;
            url: string;
        };
        OpenAdminSessionRequest: {
            login: string;
            password: string;
        };
        PageResponseAdminContactMessageSummaryResponse: {
            content: components["schemas"]["AdminContactMessageSummaryResponse"][];
            first: boolean;
            last: boolean;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseAdminMediaResponse: {
            content: components["schemas"]["AdminMediaResponse"][];
            first: boolean;
            last: boolean;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseAdminProjectSummaryResponse: {
            content: components["schemas"]["AdminProjectSummaryResponse"][];
            first: boolean;
            last: boolean;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseAdminPublicationSummaryResponse: {
            content: components["schemas"]["AdminPublicationSummaryResponse"][];
            first: boolean;
            last: boolean;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseAdminSeriesSummaryResponse: {
            content: components["schemas"]["AdminSeriesSummaryResponse"][];
            first: boolean;
            last: boolean;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseProjectSummaryResponse: {
            content: components["schemas"]["ProjectSummaryResponse"][];
            first: boolean;
            last: boolean;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponsePublicationSummaryResponse: {
            content: components["schemas"]["PublicationSummaryResponse"][];
            first: boolean;
            last: boolean;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseSearchResultResponse: {
            content: components["schemas"]["SearchResultResponse"][];
            first: boolean;
            last: boolean;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PageResponseSeriesSummaryResponse: {
            content: components["schemas"]["SeriesSummaryResponse"][];
            first: boolean;
            last: boolean;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ProfessionalLinkResponse: {
            label: string;
            url: string;
        };
        ProfileResponse: {
            aboutMarkdown: string | null;
            avatar: components["schemas"]["PublicImage"] | null;
            certifications: components["schemas"]["CertificationResponse"][];
            cv: components["schemas"]["PublicDocument"] | null;
            displayName: string;
            educations: components["schemas"]["EducationResponse"][];
            experiences: components["schemas"]["ExperienceResponse"][];
            links: components["schemas"]["ProfessionalLinkResponse"][];
            professionalTitle: string;
            publicEmail: string | null;
            publicLocation: string | null;
            shortBio: string;
            skillGroups: components["schemas"]["SkillGroupResponse"][];
        };
        ProjectResponse: {
            cover: components["schemas"]["PublicImage"] | null;
            demoUrl: string | null;
            descriptionMarkdown: string;
            /** Format: date */
            endDate: string | null;
            featured: boolean;
            repositoryUrl: string | null;
            screenshots: components["schemas"]["ProjectScreenshotResponse"][];
            shortDescription: string;
            slug: string;
            /** @enum {string} */
            stage: "IN_PROGRESS" | "COMPLETED";
            /** Format: date */
            startDate: string;
            technologies: components["schemas"]["TechnologyResponse"][];
            title: string;
        };
        ProjectScreenshotResponse: {
            caption: string | null;
            image: components["schemas"]["PublicImage"];
        };
        ProjectSummaryResponse: {
            cover: components["schemas"]["PublicImage"] | null;
            /** Format: date */
            endDate: string | null;
            featured: boolean;
            shortDescription: string;
            slug: string;
            /** @enum {string} */
            stage: "IN_PROGRESS" | "COMPLETED";
            /** Format: date */
            startDate: string;
            technologies: components["schemas"]["TechnologyResponse"][];
            title: string;
        };
        PublicDocument: {
            /** Format: int64 */
            sizeBytes: number;
            url: string;
        };
        PublicImage: {
            altText: string | null;
            /** Format: int32 */
            height: number;
            url: string;
            /** Format: int32 */
            width: number;
        };
        PublicationResponse: {
            category: components["schemas"]["TaxonomyTermResponse"] | null;
            contentMarkdown: string;
            cover: components["schemas"]["PublicImage"] | null;
            featured: boolean;
            /** Format: date-time */
            publishedAt: string;
            /** Format: int32 */
            readingTimeMinutes: number;
            seoDescription: string | null;
            seoTitle: string | null;
            slug: string;
            summary: string;
            tags: components["schemas"]["TaxonomyTermResponse"][];
            title: string;
            /** @enum {string} */
            type: "ARTICLE" | "NEWS";
        };
        PublicationSummaryResponse: {
            category: components["schemas"]["TaxonomyTermResponse"] | null;
            cover: components["schemas"]["PublicImage"] | null;
            featured: boolean;
            /** Format: date-time */
            publishedAt: string;
            /** Format: int32 */
            readingTimeMinutes: number;
            slug: string;
            summary: string;
            tags: components["schemas"]["TaxonomyTermResponse"][];
            title: string;
            /** @enum {string} */
            type: "ARTICLE" | "NEWS";
        };
        SaveCategoryRequest: {
            description?: string;
            name: string;
            slug?: string;
        };
        SaveProfileRequest: {
            aboutMarkdown?: string;
            /** Format: int64 */
            avatarMediaId?: number;
            certifications?: components["schemas"]["Certification"][];
            /** Format: int64 */
            cvMediaId?: number;
            displayName: string;
            educations?: components["schemas"]["Education"][];
            experiences?: components["schemas"]["Experience"][];
            links?: components["schemas"]["Link"][];
            professionalTitle: string;
            /** Format: email */
            publicEmail?: string;
            publicLocation?: string;
            shortBio: string;
            skills?: components["schemas"]["Skill"][];
        };
        SaveProjectRequest: {
            /** Format: int64 */
            coverMediaId?: number;
            demoUrl?: string;
            descriptionMarkdown: string;
            /** Format: int32 */
            displayOrder?: number;
            /** Format: date */
            endDate?: string;
            featured?: boolean;
            repositoryUrl?: string;
            screenshots?: components["schemas"]["Screenshot"][];
            shortDescription: string;
            slug?: string;
            /** @enum {string} */
            stage: "IN_PROGRESS" | "COMPLETED";
            /** Format: date */
            startDate: string;
            technologyIds?: number[];
            title: string;
            /** @enum {string} */
            visibility: "DRAFT" | "PUBLISHED" | "ARCHIVED";
        };
        SaveSeriesRequest: {
            /** Format: int64 */
            coverMediaId?: number;
            descriptionMarkdown: string;
            slug?: string;
            title: string;
        };
        SaveTagRequest: {
            name: string;
            slug?: string;
        };
        SaveTechnologyRequest: {
            /** Format: int32 */
            displayOrder?: number;
            name: string;
            slug?: string;
        };
        Screenshot: {
            caption?: string;
            /** Format: int64 */
            mediaId: number;
        };
        SearchResultResponse: {
            /** Format: date-time */
            publishedAt: string | null;
            slug: string;
            summary: string;
            title: string;
            /** @enum {string} */
            type: "ARTICLE" | "NEWS" | "PROJECT";
        };
        SeriesChapterResponse: {
            /** Format: int32 */
            position: number;
            /** Format: date-time */
            publishedAt: string;
            /** Format: int32 */
            readingTimeMinutes: number;
            slug: string;
            summary: string;
            title: string;
        };
        SeriesNavigationResponse: {
            /** Format: int32 */
            chapterCount: number;
            next: components["schemas"]["ChapterLinkResponse"] | null;
            /** Format: int32 */
            position: number;
            previous: components["schemas"]["ChapterLinkResponse"] | null;
            series: components["schemas"]["SeriesReferenceResponse"];
        };
        SeriesReferenceResponse: {
            slug: string;
            title: string;
        };
        SeriesResponse: {
            chapters: components["schemas"]["SeriesChapterResponse"][];
            cover: components["schemas"]["PublicImage"] | null;
            descriptionMarkdown: string;
            slug: string;
            title: string;
        };
        SeriesSummaryResponse: {
            /** Format: int32 */
            chapterCount: number;
            cover: components["schemas"]["PublicImage"] | null;
            descriptionMarkdown: string;
            slug: string;
            title: string;
        };
        Skill: {
            category: string;
            name: string;
        };
        SkillGroupResponse: {
            category: string;
            skills: components["schemas"]["SkillResponse"][];
        };
        SkillResponse: {
            name: string;
        };
        TaxonomyTermResponse: {
            name: string;
            slug: string;
        };
        TechnologyResponse: {
            name: string;
            slug: string;
        };
        UpdateMediaRequest: {
            altText?: string;
        };
        UpdatePublicationRequest: {
            /** Format: int64 */
            categoryId?: number;
            contentMarkdown: string;
            /** Format: int64 */
            coverMediaId?: number;
            featured?: boolean;
            seoDescription?: string;
            seoTitle?: string;
            slug?: string;
            summary: string;
            tagIds?: number[];
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminCategoryResponse"][];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminCategoryResponse"];
                };
            };
        };
    };
    update_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveCategoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminCategoryResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_7: {
        parameters: {
            query: {
                status?: "NEW" | "READ" | "PROCESSED" | "ARCHIVED";
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminContactMessageSummaryResponse"];
                };
            };
        };
    };
    get_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminContactMessageResponse"];
                };
            };
        };
    };
    changeStatus_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeContactMessageStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminContactMessageResponse"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminMediaResponse"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: {
                altText?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminMediaResponse"];
                };
            };
        };
    };
    get_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminMediaResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMediaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminMediaResponse"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProfileResponse"];
                };
            };
        };
    };
    update_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProfileResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminProjectSummaryResponse"];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProjectResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProjectResponse"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveProjectRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProjectResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminPublicationSummaryResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePublicationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminPublicationResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminPublicationResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePublicationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminPublicationResponse"];
                };
            };
        };
    };
    changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePublicationStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminPublicationResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminSeriesSummaryResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSeriesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSeriesResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSeriesResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSeriesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSeriesResponse"];
                };
            };
        };
    };
    changeChapters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeSeriesChaptersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSeriesResponse"];
                };
            };
        };
    };
    current: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSessionResponse"];
                };
            };
        };
    };
    open: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenAdminSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminSessionResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTagResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveTagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTagResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveTagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTagResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTechnologyResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveTechnologyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTechnologyResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveTechnologyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTechnologyResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storageKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query: {
                technology?: string;
                featured?: boolean;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseProjectSummaryResponse"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    listPublications: {
        parameters: {
            query: {
                type?: "ARTICLE" | "NEWS";
                category?: string;
                tag?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponsePublicationSummaryResponse"];
                };
            };
        };
    };
    getPublication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PublicationResponse"];
                };
            };
        };
    };
    getSeriesNavigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeriesNavigationResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseSearchResultResponse"];
                };
            };
        };
    };
    listSeries: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseSeriesSummaryResponse"];
                };
            };
        };
    };
    getSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SeriesResponse"];
                };
            };
        };
    };
}
